- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.shahulahmed.online
  tasks:
  - name: Install MySQL Server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  
  - name: Start and Enable MySQL server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  # check already password is setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_host }}"
    ilter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{mysql_connection_output}} "


